Add make integrationtest

diff --git a/svir/Makefile b/svir/Makefile
--- a/svir/Makefile
+++ b/svir/Makefile
@@ -74,6 +74,23 @@ test: compile transcompile
 	@echo "e.g. source ../scripts/run-env-linux.sh <path to qgis install>; make test"
 	@echo "----------------------"
 
+integrationtest: compile transcompile
+	@echo
+	@echo "----------------------"
+	@echo "Integration Test Suite"
+	@echo "----------------------"
+
+	@export PYTHONPATH=`pwd`:$(PYTHONPATH); \
+		export QGIS_DEBUG=0; \
+		export QGIS_LOG_FILE=/dev/null; \
+		nosetests -s -v --with-xunit --with-id test/integration\
+		3>&1 1>&2 2>&3 3>&-
+	@echo "----------------------"
+	@echo "If you get 'no module...' errors, try sourcing"
+	@echo "the helper script we have provided first then run make integrationtest."
+	@echo "e.g. source ../scripts/run-env-linux.sh <path to qgis install>; make integrationtest"
+	@echo "----------------------"
+
 deploy: compile doc transcompile
 	@echo
 	@echo "------------------------------------------"
