Wait for X environment to be ready before running unit tests (actually checking rather than just waiting for a while)

diff --git a/.github/workflows/qgis_ltr_engine_releases.yml b/.github/workflows/qgis_ltr_engine_releases.yml
--- a/.github/workflows/qgis_ltr_engine_releases.yml
+++ b/.github/workflows/qgis_ltr_engine_releases.yml
@@ -142,7 +142,17 @@ jobs:
           docker run -d -t --name qgis -v /tmp/.X11-unix:/tmp/.X11-unix -v ${PWD}:/tests_directory -e OQ_ENGINE_HOST='http://172.17.0.1:8800' \
             -e BRANCH="$IRMT_BR" -e ONLY_CALC_ID="$ONLY_CALC_ID" -e ONLY_OUTPUT_TYPE="$ONLY_OUTPUT_TYPE" -e GEM_QGIS_TEST=y ${{ matrix.QGIS_DOCKER_VERSION }} \
             bash -c "/tests_directory/startX.sh"
-          sleep 30  # wait for startX environment to complete setup (to be improved)
+          while [ ! -e /tmp/.X11-unix/X1 ] && [ $COUNT -lt 20 ];
+          do
+            echo waiting for X $COUNT..;
+            sleep 3;
+            let COUNT++;
+          done
+          if [ ! -e /tmp/.X11-unix/X1 ]
+          then
+            echo "X environment still not ready, aborting";
+            exit 1;
+          fi
       - name: ℧ Run unit test
         run: |
           set -x
