Backport and adapt test_push.yml from master

diff --git a/.github/workflows/test_push.yml b/.github/workflows/test_push.yml
--- a/.github/workflows/test_push.yml
+++ b/.github/workflows/test_push.yml
@@ -1,5 +1,12 @@
 name: PR unit and integration tests
 on:
+  workflow_dispatch:
+    inputs:
+      debug_enabled:
+        type: boolean
+        description: "Run the build with tmate debugging enabled"
+        required: false
+        default: false
   push:
     branches:
       - '**'
@@ -8,6 +15,7 @@ on:
 
 jobs:
   Tests_and_docs:
+    name: ${{ matrix.QGIS_DOCKER_VERSION }} Py${{ matrix.PYTHON_VERSION }} ${{ matrix.ENGINE_APPLICATION_MODE }}
     strategy:
       fail-fast: false
       matrix:
@@ -16,12 +24,15 @@ jobs:
         os: [ubuntu-latest]
         # NOTE: we might test also for qgis/qgis:3.22 that is the version of qgis-server that we are currently using in the Geoviewer, but it currently causes a segfault
         # NOTE: qgis:stable points to the latest release, wheread qgis:latest points to qgis master
-        QGIS_DOCKER_VERSION: ['qgis/qgis:ltr', 'qgis/qgis:stable']
+        # QGIS_DOCKER_VERSION: ['qgis/qgis:ltr', 'qgis/qgis:stable']
+        QGIS_DOCKER_VERSION: ['qgis/qgis:ltr']
         # NOTE: qgis uses its own python, but we want to check if there are problems interfacing with the engine while it uses different python versions
         PYTHON_VERSION: ['3.10', '3.11', '3.12']
+        ENGINE_APPLICATION_MODE: ['PUBLIC']
     runs-on: ${{ matrix.os }}
     env:
       GITHUB_DEF_BR: master
+      OQ_APPLICATION_MODE: ${{ matrix.ENGINE_APPLICATION_MODE }}
     steps:
       - uses: actions/checkout@v4
       - name: 🐍 Set up Python
@@ -34,22 +45,14 @@ jobs:
           $(cat << EOF  > ./startX.sh
           apt update --allow-releaseinfo-change
           DEBIAN_FRONTEND=noninteractive apt install -y python3-scipy python3-matplotlib python3-pyqt5.qtwebkit python3-pytest python3-pexpect xvfb git expect
-          chmod +x /tests_directory/qgis_startup.py
-          cp /tests_directory/qgis_startup.py /usr/bin/
-          cp /tests_directory/qgis_testrunner.py /usr/bin/
           export DISPLAY=:1.0
           Xvfb :1 -screen 0 1024x768x16
           EOF
           )
-          curl -O https://raw.githubusercontent.com/qgis/QGIS/master/.docker/qgis_resources/test_runner/qgis_setup.sh
-          curl -O https://raw.githubusercontent.com/qgis/QGIS/master/.docker/qgis_resources/test_runner/qgis_testrunner.sh
-          curl -O https://raw.githubusercontent.com/qgis/QGIS/master/.docker/qgis_resources/test_runner/qgis_testrunner.py
-          curl -O https://raw.githubusercontent.com/qgis/QGIS/master/.docker/qgis_resources/test_runner/qgis_startup.py
-          chmod +x ./qgis_setup.sh
-          chmod +x ./qgis_testrunner.sh
-          chmod +x ./qgis_testrunner.py
           chmod +x ./startX.sh
-      - name: ⏳ Install engine and restore oqdata and docker container
+      - name: ⏳ Clone/install engine and restore oqdata and docker container
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           PY_VER=${{ matrix.PYTHON_VERSION }}
           echo "Python version to use: $PY_VER"
@@ -76,7 +79,9 @@ jobs:
           echo "Restore OQ-Engine demos for $ENGINE_BR branch "
           source $HOME/openquake/bin/activate
           oq reset -y
+          echo "Restore OQ-Engine demos for $ENGINE_BR branch "
           oq restore https://artifacts.openquake.org/travis/oqdata-${ENGINE_BR}.zip ~/oqdata
+          python $HOME/openquake/lib/python$PY_VER/site-packages/openquake/server/manage.py migrate
           oq --version
           oq webui start 172.17.0.1:8800 --skip-browser &> webui.log &
           echo "Waiting WEBUI up on port 8800...."
@@ -91,12 +96,28 @@ jobs:
           docker run -d -t --name qgis -v /tmp/.X11-unix:/tmp/.X11-unix -v ${PWD}:/tests_directory -e OQ_ENGINE_HOST='http://172.17.0.1:8800' \
             -e BRANCH="$IRMT_BR" -e ONLY_CALC_ID="$ONLY_CALC_ID" -e ONLY_OUTPUT_TYPE="$ONLY_OUTPUT_TYPE" -e GEM_QGIS_TEST=y ${{ matrix.QGIS_DOCKER_VERSION }} \
             bash -c "/tests_directory/startX.sh"
-          sleep 10
+
+          COUNT=0
+          SOCKET=/tmp/.X11-unix/X1
+          MAX_TRIES=20
+          while [ ! -S "$SOCKET" ] && [ "$COUNT" -lt "$MAX_TRIES" ]; do
+              echo "waiting for X ($COUNT)..."
+              sleep 3
+              COUNT=$((COUNT + 1))
+          done
+          if [ ! -S "$SOCKET" ]; then
+              echo "X environment still not ready, aborting"
+              exit 1
+          fi
+      - name: Setup debugging session
+        uses: mxschmitt/action-tmate@v3
+        timeout-minutes: 60
+        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
       - name: ℧ Run unit test
         run: |
           set -x
           # OGR_SQLITE_JOURNAL=delete prevents QGIS from using WAL, which modifies geopackages even if they are just read
-          docker exec -t qgis bash -c "export DISPLAY=:1.0; export PYTHONPATH=/usr/share/qgis/python/plugins/:$PYTHONPATH; OGR_SQLITE_JOURNAL=delete python3 -m pytest -v /tests_directory/svir/test/unit/"
+          docker exec -t qgis bash -c "export DISPLAY=:1.0; export PYTHONPATH=/usr/share/qgis/python/plugins/:$PYTHONPATH; OGR_SQLITE_JOURNAL=delete python3 -m pytest -v -s -ra /tests_directory/svir/test/unit/"
       - name: ⨕ Run Integration test
         run: |
           set -x
@@ -116,8 +137,7 @@ jobs:
           fi
           # NOTE: cloning the engine is needed to find the demos directory, therefore being able to test running a calculation
           docker exec qgis sh -c "export DISPLAY=:1.0; git clone -q -b $ENGINE_BR --depth=1 https://github.com/gem/oq-engine.git && echo 'Running against oq-engine/$GITHUB_BR'"
-          docker exec qgis sh -c "export DISPLAY=:1.0; /tests_directory/qgis_setup.sh svir"
-          docker exec -t qgis sh -c "export DISPLAY=:1.0; cd /tests_directory && ./qgis_testrunner.sh svir.test.integration.test_drive_oq_engine"
+          docker exec -t qgis bash -c "export DISPLAY=:1.0; export PYTHONPATH=/usr/share/qgis/python/plugins/:$PYTHONPATH; python3 -m pytest -v -s -ra /tests_directory/svir/test/integration/"
       - name: 📖 Make documentation
         run: |
           set -x
